### ISSUE TITLE
Yaml parser

### ISSUE THREAD

**Issue by vitxd** [igorw/ConfigServiceProvider#51]
Hello, not sure is something I'm doing wrong or what, but I can't make the yaml parser work with the library used as is.
With a minor change in your code however, YamlConfigDriver line 14, I managed to make it work.

Basically instead of passing the filename to the Yaml::parse method I pass the file_get_contents it works like a charm.

Should I do a pull request?

**Comment by vitxd** [comment]
I just noticed you already have a pull request for that

https://github.com/igorw/ConfigServiceProvider/pull/46/files

**Comment by ollyollyollyltd** [comment]
Seconding this; the YAML parser is broken as is but the pull request linked by @vitxd fixes it.

**Comment by SelrahcD** [comment]
I have the same issue and managed to deal with it.
The PR is not the appropriate fix I think.

This lib suggests to install `symfony/yaml`and does not require it. When composer checks for dependencies it doesn't care that the lib suggests to install `~2.1`.
You may have another dependency dealing with `symfony/yaml` in `3.*` and thus composer installs an according version. The Yaml parser in v3 changed the way it takes it inputs (yaml string instead of file path) which breaks this lib.

You should require "symfony/yaml" in a v2 version in your project in order to fix the issue. Composer update will potentially fail if one of our depencies is strict about needing a v3 version of `symfony/yaml` but this is normal.
